/* ============================================================
   Lesson 4.2 - Fiscal policy
   Cambridge IGCSE Economics 0455 - Unit 4: Government and the macroeconomy

   Syllabus source:
   ../../../references/igcse-economics-syllabus-2027-2029.md

   Pacing note:
   Keep each slide to one teaching move and tie each policy effect back to
   the macroeconomic aims taught in 4.1.1.
   ============================================================ */

window.IGCSE = window.IGCSE || {};

const photos = IGCSE.photos.fiscalPolicy;
const factPhotos = IGCSE.photos.fiscalPolicyFacts;
IGCSE.lesson = {
  meta: {
    code:         '4.2',
    unit:         'Unit 4 - Government and the macroeconomy',
    title:        'Fiscal policy - Cambridge IGCSE Economics 0455',
    lessonLabel:  'Fiscal policy',
    courseLabel:  'Cambridge IGCSE Economics 0455',
    creatorLabel: 'Created by Samuel Oehler-Huang, Suzhou Foreign Language School',
  },

  slides: [
    {
      type: 'hero',
      eyebrow:  'Lesson overview',
      title:    'Fiscal policy',
      zhTitle: '财政政策',
      subtitle: 'Government spending and taxation',
      kicker:   'How can a budget help meet macroeconomic aims?',
    },
    {
      type: 'outcomes',
      eyebrow: 'Objectives',
      title:   'By the end, you can',
      bullets: [
        'Calculate deficits and surpluses.',
        'Explain spending and taxation.',
        'Classify tax types.',
        'Link fiscal policy to macro aims.',
      ],
    },
    {
      type: 'roadmap',
      eyebrow: 'Lesson overview',
      title:   'Today\'s route',
      items: [
        ['4.2.1', 'Budget', 'revenue, expenditure, deficit, surplus'],
        ['4.2.2', 'Spending', 'main areas, reasons and effects'],
        ['4.2.3', 'Taxation', 'reasons and types of taxes'],
        ['4.2.4-4.2.6', 'Fiscal policy', 'measures and effects on macro aims'],
      ],
      visual: photos.budgetHearing,
    },
    {
      type: 'quiz',
      eyebrow: 'Starter',
      title:   'You control the budget',
      question: 'Growth is slowing, unemployment is rising, prices are still increasing, and pollution is high. What should the government prioritise?',
      choices: [
        'Economic growth',
        'Low unemployment',
        'Low inflation',
        'Environmental sustainability',
      ],
      prompt: 'Choose one aim, then name the likely trade-off.',
      visual: photos.budgetMeeting,
    },
    {
      type: 'discussion',
      eyebrow: 'Starter',
      title:   'Trade-offs',
      question: 'What should a government do first when it cannot achieve every aim at once?',
      zh: '当政府无法同时实现所有目标时，应该先做什么？',
      answer: 'It should prioritise the most urgent aim and accept that there may be trade-offs with other aims.',
      answerZh: '政府应优先处理最紧迫的目标，并承认这可能与其他目标存在取舍。',
      visual: photos.budgetMeeting,
    },

    {
      type: 'section',
      eyebrow: 'New section',
      title:   'Government budget',
      zhTitle: '政府预算',
      subtitle: 'Revenue and expenditure decide whether there is a deficit or surplus.',
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'Public money',
      question: 'What should happen if a government spends more than it receives?',
      zh: '如果政府支出超过收入，应该怎么办？',
      answer: 'It has a budget deficit, so it may need to borrow, raise revenue, or reduce some spending.',
      answerZh: '这会形成预算赤字，因此政府可能需要借款、增加收入或削减部分支出。',
      visual: photos.budgetHearing,
    },
    {
      type: 'term',
      eyebrow: 'Learn',
      title:   'Budget balance',
      zhTitle: '预算差额',
      term:    'government budget',
      definition: 'A government budget is a plan or forecast for government revenue and government expenditure.',
      definitionZh: '政府预算是政府收入和政府支出的计划或预测。',
      formula: 'Budget balance = government revenue - government expenditure',
      examples: ['negative balance = deficit', 'positive balance = surplus'],
      visual:  photos.budgetMeeting,
      partialReview: ['.termBox', '.formula', '.choices > .choice'],
    },
    {
      type: 'fact',
      eyebrow: 'Example',
      facts: {
        left: {
          flag: '🇬🇧',
          country: 'United Kingdom',
          context: 'UK public borrowing was GBP 131.1 billion (about RMB 1.2 trillion) in 2023/24.',
          question: 'How is a budget deficit linked to government borrowing?',
          questionZh: '预算赤字与政府借款有什么联系？',
          answer: 'A budget deficit means government spending exceeds revenue, so the government usually needs to borrow.',
          zh: '2023/24财年，英国公共借款为1311亿英镑（约1.2万亿元人民币）。',
          source: 'Source: UK ONS; RMB conversion approximate.',
        },
        china: {
          flag: '🇨🇳',
          country: 'China',
          context: 'China planned a RMB 4.06 trillion budget deficit in 2024, equal to 3% of GDP.',
          question: 'How is a budget deficit linked to government borrowing?',
          questionZh: '预算赤字与政府借款有什么联系？',
          answer: 'A budget deficit means government spending exceeds revenue, so the government usually needs to borrow.',
          zh: '中国2024年安排预算赤字4.06万亿元人民币，相当于GDP的3%。',
          source: 'Source: 2024 Government Work Report.',
        },
      },
      visual: factPhotos.ukBudget,
    },
    {
      type: 'quiz',
      eyebrow: 'Check',
      title:   'Deficit or surplus?',
      question: 'Government revenue = $420m. Government expenditure = $510m.',
      choices: ['$90m surplus', '$90m deficit', '$930m deficit'],
      prompt:  'Calculate revenue - expenditure.',
      visual:  photos.taxForms,
    },
    {
      type: 'answer',
      eyebrow: 'Check',
      title:   'Answer',
      answer:  '$90m deficit',
      body:    '$420m - $510m = -$90m. A deficit occurs because spending is greater than revenue.',
      visual:  photos.budgetMeeting,
      partialReview: ['.answerBox'],
    },
    {
      type: 'compare',
      eyebrow: 'Learn',
      title:   'Deficit or surplus?',
      leftTitle:  'Budget deficit',
      left:  ['government spending exceeds government revenue', 'may require borrowing'],
      rightTitle: 'Budget surplus',
      right: ['government revenue exceeds government spending', 'may reduce borrowing or debt'],
      prompt: 'A balanced budget means revenue equals expenditure.',
      visual: photos.budgetHearing,
      partialReview: ['.splitCols > .card', '.prompt'],
    },

    {
      type: 'section',
      eyebrow: 'New section',
      title:   'Government spending',
      zhTitle: '政府支出',
      subtitle: 'Main areas of spending have different macroeconomic effects.',
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'Priorities',
      question: 'Which area of government spending should receive more money first?',
      zh: '政府支出的哪个领域应该最先获得更多资金？',
      answer: 'A strong answer chooses one area, such as healthcare or education, and explains the likely benefit and opportunity cost.',
      answerZh: '好的回答应选择一个领域，如医疗或教育，并解释可能的收益和机会成本。',
      visual: photos.budgetHearing,
    },
    {
      type: 'cards',
      eyebrow: 'Learn',
      title:   'Main areas of spending',
      cards: [
        ['Education', 'schools and training'],
        ['Healthcare', 'hospitals and public health'],
        ['Infrastructure', 'transport and digital networks'],
        ['Welfare', 'benefits and pensions'],
        ['Defence', 'national security'],
        ['Industry support', 'subsidies and research'],
      ],
      visual: photos.budgetHearing,
      partialReview: ['.cardgrid > .card'],
    },
    {
      type: 'fact',
      eyebrow: 'Example',
      facts: {
        left: {
          flag: '🇫🇮',
          country: 'Finland',
          context: 'Finland’s government education spending was 6.38% of GDP in 2022.',
          question: 'Which government spending aim could education support?',
          questionZh: '教育支出可能支持哪个政府支出目标？',
          answer: 'Education spending can support long-run growth by improving human capital and productivity.',
          zh: '2022年，芬兰政府教育支出占GDP的6.38%。',
          source: 'Source: World Bank, based on UNESCO UIS data.',
        },
        china: {
          flag: '🇨🇳',
          country: 'China',
          context: 'China spent RMB 6.4595 trillion on education in 2023.',
          question: 'Which government spending aim could education support?',
          questionZh: '教育支出可能支持哪个政府支出目标？',
          answer: 'Education spending can support long-run growth by improving human capital and productivity.',
          zh: '2023年，中国教育经费总投入达到6.4595万亿元人民币。',
          source: 'Source: China Ministry of Education.',
        },
      },
      visual: factPhotos.finlandEducation,
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'Why spend?',
      question: 'Why might markets fail to provide enough education, healthcare or infrastructure?',
      zh: '为什么市场可能无法提供足够的教育、医疗或基础设施？',
      answer: 'Markets may under-provide them because benefits spill over to society or because some people cannot afford the full price.',
      answerZh: '市场可能提供不足，因为这些服务的收益会扩散到社会，或有些人无法承担全部价格。',
      visual: photos.classroom,
    },
    {
      type: 'cards',
      eyebrow: 'Learn',
      title:   'Why governments spend',
      cards: [
        ['Merit goods', 'education, healthcare', '1'],
        ['Public goods', 'defence', '2'],
        ['Infrastructure', 'roads, rail, ports', '3'],
        ['Key industries', 'subsidies, R&D', '4'],
        ['Inequality', 'benefits, pensions', '5'],
        ['Macroeconomy', 'demand, inflation', '6'],
      ],
      visual: photos.budgetHearing,
      partialReview: ['.cardgrid > .card'],
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'Education and healthcare',
      question: 'Why might a person consume too little education or healthcare if they must pay the full price?',
      zh: '如果必须支付全部价格，为什么人们可能消费太少的教育或医疗？',
      answer: 'They may focus on the private cost and ignore wider long-term benefits, or simply be unable to afford it.',
      answerZh: '他们可能只看到私人费用而忽视长期广泛收益，或者根本负担不起。',
      visual: photos.classroom,
    },
    {
      type: 'flow',
      eyebrow: 'Learn',
      title:   '1. Provide merit goods',
      zhTitle: '提供有益品',
      question: 'Education and healthcare may be underprovided if people have to pay the full price.',
      nodes: [['government funds schools or hospitals', 'more people can access them', 'skills and health improve', 'productivity may rise']],
      footer: 'Exam link: merit goods can improve living standards and long-run growth.',
      visual: photos.classroom,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'Free rider problem',
      question: 'Why is defence difficult to sell only to people who pay for it?',
      zh: '为什么国防很难只卖给付费的人？',
      answer: 'Defence is non-excludable: once provided, people in the country are protected even if they did not pay directly.',
      answerZh: '国防具有非排他性：一旦提供，国内居民即使没有直接付费也会受到保护。',
      visual: photos.defence,
    },
    {
      type: 'flow',
      eyebrow: 'Learn',
      title:   '2. Provide public goods',
      zhTitle: '提供公共物品',
      question: 'Some goods would not be provided by private firms because people can benefit without paying directly.',
      nodes: [['government funds defence', 'the country is protected', 'people and firms face less risk', 'economic activity is protected']],
      footer: 'Exam link: public goods create benefits that markets may not provide.',
      visual: photos.defence,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'Roads, rail and ports',
      question: 'How can a better road or railway help firms produce more?',
      zh: '更好的公路或铁路如何帮助企业生产更多？',
      answer: 'Better infrastructure can reduce transport time and costs, helping firms move inputs and goods more efficiently.',
      answerZh: '更好的基础设施可以减少运输时间和成本，帮助企业更高效地运输投入品和商品。',
      visual: photos.roadwork,
    },
    {
      type: 'flow',
      eyebrow: 'Learn',
      title:   '3. Invest in infrastructure',
      zhTitle: '投资基础设施',
      nodes: [['more infrastructure spending', 'lower transport costs', 'firms may produce more', 'real GDP may rise']],
      footer: 'This links spending to economic growth.',
      visual: photos.roadwork,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'quiz',
      eyebrow: 'Check',
      question: 'The government builds a new railway between factories and a port. Which reason for spending is most direct?',
      choices: [
        'Provide a public good',
        'Invest in infrastructure',
        'Reduce inequality',
      ],
      prompt: 'Say the answer, then add one likely effect on firms.',
      visual: photos.roadwork,
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'Picking winners',
      question: 'Should a government support an industry if it is important for future jobs?',
      zh: '如果某个产业对未来就业很重要，政府应该支持它吗？',
      answer: 'It may support the industry if future benefits are large, but it should consider opportunity cost and possible inefficiency.',
      answerZh: '如果未来收益很大，政府可以支持该产业，但应考虑机会成本和可能的低效率。',
      visual: photos.industry,
    },
    {
      type: 'fact',
      eyebrow: 'Example',
      facts: {
        left: {
          flag: '🇺🇸',
          country: 'United States',
          context: 'The US CHIPS Act offered $52.7 billion (about RMB 380 billion) for semiconductors.',
          question: 'How could this support investment, output and employment?',
          questionZh: '这会如何支持投资、产量和就业？',
          answer: 'It can raise investment first, then increase productive capacity, output and employment if firms expand.',
          zh: '《芯片法案》为美国半导体产业提供527亿美元（约3800亿元人民币）。',
          source: 'Source: NIST; RMB conversion approximate.',
        },
        china: {
          flag: '🇨🇳',
          country: 'China',
          context: 'China’s Big Fund III had RMB 344 billion registered capital.',
          question: 'How could this support investment, output and employment?',
          questionZh: '这会如何支持投资、产量和就业？',
          answer: 'It can raise investment first, then increase productive capacity, output and employment if firms expand.',
          zh: '中国大基金三期注册资本为3440亿元人民币。',
          source: 'Source: Gov.cn.',
        },
      },
      visual: factPhotos.usSemiconductors,
    },
    {
      type: 'flow',
      eyebrow: 'Learn',
      title:   '4. Support key industries',
      zhTitle: '支持关键产业',
      question: 'Governments may support industries that are important for jobs, exports or future technology.',
      nodes: [['subsidy for a key industry', 'firms face lower costs', 'investment or R&D may rise', 'competitiveness may improve']],
      footer: 'Evaluation: subsidies have an opportunity cost and may protect inefficient firms.',
      visual: photos.industry,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'Welfare support',
      question: 'How much responsibility should a government take for reducing poverty?',
      zh: '政府在减少贫困方面应该承担多大责任？',
      answer: 'Governments often redistribute income through taxes and spending, but the extent depends on priorities and costs.',
      answerZh: '政府通常通过税收和支出来再分配收入，但承担程度取决于优先目标和成本。',
      visual: photos.socialSecurity,
    },
    {
      type: 'flow',
      eyebrow: 'Learn',
      title:   '5. Reduce inequality',
      zhTitle: '减少不平等',
      nodes: [['higher welfare spending', 'poorer households receive support', 'income inequality may fall']],
      footer: 'Add a cost: the government may need higher taxes or borrowing.',
      visual: photos.socialSecurity,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'Managing demand',
      question: 'Should a government spend more when unemployment is rising?',
      zh: '当失业率上升时，政府应该增加支出吗？',
      answer: 'It may increase spending to raise aggregate demand and employment, but this could increase borrowing or inflationary pressure.',
      answerZh: '政府可以增加支出来提高总需求和就业，但这可能增加借款或通胀压力。',
      visual: photos.budgetMeeting,
    },
    {
      type: 'flow',
      eyebrow: 'Learn',
      title:   '6. Manage the macroeconomy',
      zhTitle: '管理宏观经济',
      question: 'Government spending can be changed to influence aggregate demand.',
      nodes: [['higher government spending', 'aggregate demand rises', 'firms may increase output', 'growth and employment may rise']],
      footer: 'Evaluation: demand may rise too much and create inflationary pressure.',
      visual: photos.budgetMeeting,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'quiz',
      eyebrow: 'Check',
      question: 'The government increases unemployment benefits during a downturn. Which reason fits best?',
      choices: [
        'Reduce inequality',
        'Support key industries',
        'Provide public goods',
      ],
      prompt: 'Now name one possible opportunity cost.',
      visual: photos.socialSecurity,
    },
    {
      type: 'quiz',
      eyebrow: 'Apply',
      question: 'Which spending decision most directly supports environmental sustainability?',
      choices: [
        'Build cleaner public transport',
        'Increase debt-interest payments',
        'Cut education spending',
      ],
      prompt: 'Now add one possible opportunity cost.',
      visual: photos.pollution,
    },

    {
      type: 'section',
      eyebrow: 'New section',
      title:   'Taxation',
      zhTitle: '税收',
      subtitle: 'Taxes raise revenue, change behaviour and influence aggregate demand.',
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'Every receipt is a policy choice',
      question: 'Which taxes do you already know?',
      zh: '你已经知道哪些税？',
      answer: 'Examples include income tax, corporation tax, VAT or sales tax, excise duty, tariffs and environmental taxes.',
      answerZh: '例子包括所得税、公司税、增值税或销售税、消费税、关税和环境税。',
      visual: photos.shopping,
    },
    {
      type: 'outcomes',
      eyebrow: 'Objectives',
      title:   'By the end of the taxation lesson, you can',
      bullets: [
        'Explain reasons for taxation.',
        'Distinguish between direct and indirect tax.',
        'Distinguish between proportional, progressive and regressive tax.',
        'Use real examples.',
      ],
      visual: photos.taxForms,
    },
    {
      type: 'quiz',
      eyebrow: 'Starter',
      title:   'What do you already know?',
      question: 'Which statement is most accurate?',
      choices: [
        'All taxes are paid directly by households to the government.',
        'Some taxes are paid on income; others are paid when goods and services are bought.',
        'A tax can only raise revenue and cannot change behaviour.',
      ],
      prompt: 'Choose one, then correct one wrong statement.',
      visual: photos.taxForms,
    },
    {
      type: 'fact',
      eyebrow: 'Example',
      facts: {
        left: {
          flag: '🇩🇰',
          country: 'Denmark',
          context: 'Denmark’s tax revenue was 45.2% of GDP in 2024.',
          question: 'How does tax revenue help finance government spending?',
          questionZh: '税收收入如何帮助政府支出融资？',
          answer: 'Tax revenue gives the government funds to pay for public services, transfers and investment.',
          zh: '2024年，丹麦税收收入占GDP的45.2%。',
          source: 'Source: OECD Revenue Statistics 2025.',
        },
        china: {
          flag: '🇨🇳',
          country: 'China',
          context: 'China’s tax revenue was 20.4% of GDP in 2023.',
          question: 'How does tax revenue help finance government spending?',
          questionZh: '税收收入如何帮助政府支出融资？',
          answer: 'Tax revenue gives the government funds to pay for public services, transfers and investment.',
          zh: '2023年，中国税收收入占GDP的20.4%。',
          source: 'Source: OECD Revenue Statistics in Asia and the Pacific 2025.',
        },
      },
      visual: factPhotos.denmarkTax,
    },
    {
      type: 'flow',
      eyebrow: 'Learn',
      title:   '1. Raise revenue',
      zhTitle: '增加财政收入',
      nodes: [['government charges taxes', 'revenue rises', 'public services can be funded']],
      footer: 'Example: income tax can help fund education and healthcare.',
      visual: photos.taxForms,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'flow',
      eyebrow: 'Learn',
      title:   '2. Reduce demerit goods',
      zhTitle: '减少有害品',
      nodes: [['tax on cigarettes', 'price rises', 'quantity demanded may fall', 'health costs may fall']],
      footer: 'Evaluation: demand may be price inelastic.',
      visual: photos.tobacco,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'fact',
      eyebrow: 'Example',
      facts: {
        left: {
          flag: '🇦🇺',
          country: 'Australia',
          context: 'Australia’s cigarette excise tax was AUD 1.40312 per stick (about RMB 6.7) in March 2025.',
          question: 'How could a cigarette tax reduce consumption of a demerit good?',
          questionZh: '为什么教育可能是消费不足的有益品？',
          answer: 'Education can be under-consumed because people may underestimate its private and external benefits.',
          zh: '2025年3月，澳大利亚香烟消费税为每支1.40312澳元（约6.7元人民币）。',
          source: 'Source: Australian Taxation Office; RMB conversion approximate.',
        },
        china: {
          flag: '🇨🇳',
          country: 'China',
          context: 'China’s Class A cigarettes face a 56% production excise tax plus 11% wholesale excise tax.',
          question: 'How could a cigarette tax reduce consumption of a demerit good?',
          questionZh: '为什么教育可能是消费不足的有益品？',
          answer: 'Education can be under-consumed because people may underestimate its private and external benefits.',
          zh: '中国甲类卷烟征收56%生产环节消费税，另加11%批发环节消费税。',
          source: 'Source: China consumption tax rate table.',
        },
      },
      visual: factPhotos.philippinesTobacco,
    },
    {
      type: 'flow',
      eyebrow: 'Learn',
      title:   '3. Reduce imports',
      zhTitle: '减少进口',
      nodes: [['tariff on imports', 'import prices rise', 'consumers may buy fewer imports', 'domestic firms may sell more']],
      footer: 'Evaluation: other countries may retaliate.',
      visual: photos.port,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'quiz',
      eyebrow: 'Check',
      question: 'A government increases tax on alcohol. Which reason for taxation is most direct?',
      choices: [
        'Raise revenue only',
        'Reduce consumption of a demerit good',
        'Reduce imports',
      ],
      prompt: 'Add one reason why the effect may be limited.',
      visual: photos.tobacco,
    },
    {
      type: 'flow',
      eyebrow: 'Learn',
      title:   '4. Redistribute income',
      zhTitle: '收入再分配',
      nodes: [['higher taxes on high incomes', 'government revenue rises', 'welfare can be funded', 'inequality may fall']],
      footer: 'Progressive taxes are usually linked most directly to redistribution.',
      visual: photos.socialSecurity,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'flow',
      eyebrow: 'Learn',
      title:   '5. Influence demand',
      zhTitle: '影响需求',
      nodes: [['higher income tax', 'disposable income falls', 'consumer spending may fall', 'inflationary pressure may fall']],
      footer: 'This may conflict with growth and employment.',
      visual: photos.inflation,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'flow',
      eyebrow: 'Learn',
      title:   '6. Encourage sustainability',
      zhTitle: '鼓励可持续发展',
      nodes: [['pollution tax', 'firms face higher costs for polluting', 'cleaner methods become more attractive']],
      footer: 'Evaluate: firms may pass higher costs to consumers.',
      visual: photos.pollution,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'quiz',
      eyebrow: 'Check',
      question: 'A pollution tax raises money and makes pollution more expensive. Which answer is strongest?',
      choices: [
        'It can raise revenue and encourage sustainability',
        'It can only raise revenue',
        'It can only reduce imports',
      ],
      prompt: 'Explain why one tax can have more than one effect.',
      visual: photos.pollution,
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'Who should pay?',
      question: 'If the government needs more revenue for hospitals, should it raise income tax, VAT, corporation tax or a tax on unhealthy products?',
      zh: '如果政府需要更多收入来资助医院，应该提高所得税、增值税、公司税，还是对不健康产品征税？',
      answer: 'A strong answer chooses one tax and explains revenue, fairness, incentives and possible side effects.',
      answerZh: '好的回答应选择一种税，并解释收入、公平性、激励作用和可能的副作用。',
      visual: photos.healthcare,
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'Income and wealth',
      question: 'Should higher-income households pay a higher percentage of their income in tax?',
      zh: '高收入家庭是否应该缴纳更高比例的收入作为税？',
      answer: 'A progressive tax can reduce inequality, but very high rates may reduce incentives or encourage avoidance.',
      answerZh: '累进税可以减少不平等，但过高税率可能削弱激励或鼓励避税。',
      visual: photos.taxForms,
    },
    {
      type: 'term',
      eyebrow: 'Learn',
      title:   'Direct tax',
      zhTitle: '直接税',
      term:    'direct tax',
      definition: 'A direct tax is a tax on income, profit or wealth, paid directly by the taxpayer to the government.',
      definitionZh: '直接税是对收入、利润或财富征收、由纳税人直接向政府缴纳的税。',
      examples: ['income tax on wages', 'corporation tax on company profits', 'property tax on land or buildings'],
      visual: photos.taxForms,
      partialReview: ['.termBox', '.choices > .choice'],
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'At the checkout',
      question: 'Is a tax added to prices fair if poorer households spend most of their income?',
      zh: '如果较贫困家庭会花掉大部分收入，加在价格上的税公平吗？',
      answer: 'It may be unfair because poorer households can pay a higher share of their income through indirect taxes.',
      answerZh: '这可能不公平，因为较贫困家庭可能把更高比例的收入用于缴纳间接税。',
      visual: photos.shopping,
    },
    {
      type: 'term',
      eyebrow: 'Learn',
      title:   'Indirect tax',
      zhTitle: '间接税',
      term:    'indirect tax',
      definition: 'An indirect tax is a tax on spending. It is added to the price of goods or services and collected by the seller for the government.',
      definitionZh: '间接税是对支出征收的税。它被加到商品或服务价格中，并由销售者代政府收取。',
      examples: ['VAT on many goods and services', 'sales tax at a shop checkout', 'indirect tax on petrol or cigarettes'],
      visual: photos.shopping,
      partialReview: ['.termBox', '.choices > .choice'],
    },
    {
      type: 'indirectTaxSim',
      eyebrow: 'Explore',
      title:   'Why indirect taxes can be regressive',
      taxRate: 10,
    },
    {
      type: 'fact',
      eyebrow: 'Example',
      facts: {
        left: {
          flag: '🇬🇧',
          country: 'United Kingdom',
          context: 'After the UK sugar levy, sugar in taxed soft drinks fell 46% from 2015 to 2020.',
          question: 'How could a tax change firms\' incentives and consumer choices?',
          questionZh: '税收会如何改变企业激励和消费者选择？',
          answer: 'A tax can raise prices or encourage reformulation, so consumers buy less and firms reduce sugar content.',
          zh: '英国含糖饮料税后，被征税软饮料含糖量在2015至2020年下降46%。',
          source: 'Source: HM Treasury and HMRC.',
        },
        china: {
          flag: '🇨🇳',
          country: 'China',
          context: 'China has no national sugar-sweetened beverage excise tax in this international policy dataset.',
          question: 'What might happen to consumption if no sugar-sweetened beverage tax is used?',
          questionZh: '如果不征收含糖饮料税，消费可能会怎样？',
          answer: 'A tax can raise prices or encourage reformulation, so consumers buy less and firms reduce sugar content.',
          zh: '世界银行数据库显示，中国全国层面的含糖饮料消费税为0。',
          source: 'Source: World Bank Global SSB Tax Database.',
        },
      },
      visual: factPhotos.ukSugar,
    },
    {
      type: 'compare',
      eyebrow: 'Learn',
      title:   'Two direct taxes',
      leftTitle: 'Income tax',
      left: [
        'tax on wages, salaries or other personal income',
        'often progressive: higher earners may pay a higher percentage'
      ],
      rightTitle: 'Corporation tax',
      right: [
        'tax on company profits',
      ],
      prompt: 'Real-world link: the UK, US, China and many other countries use both taxes.',
      visual: photos.industry,
      partialReview: ['.splitCols > .card', '.prompt'],
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'Taxing company profits',
      question: 'If corporation tax rises, what might a firm do with prices, wages, investment or dividends?',
      zh: '如果公司税上升，企业可能会如何调整价格、工资、投资或股息？',
      answer: 'A firm may raise prices, limit wage growth, reduce investment, or pay lower dividends to shareholders.',
      answerZh: '企业可能提高价格、限制工资增长、减少投资，或向股东支付更低股息。',
      visual: photos.industry,
    },
    {
      type: 'compare',
      eyebrow: 'Learn',
      title:   'VAT, sales tax and other indirect taxes',
      leftTitle: 'VAT or sales tax',
      left: [
        'indirect tax on spending',
        'charged as a percentage of the selling price',
        'real examples: VAT in the UK and EU; sales tax in many US states'
      ],
      rightTitle: 'Indirect tax on specific goods',
      right: [
        'indirect tax on specific goods',
        'often used on cigarettes, alcohol and fuel',
        'aims can include revenue and reducing demerit goods'
      ],
      visual: photos.tobacco,
      partialReview: ['.splitCols > .card', '.prompt'],
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'Taxing harmful goods',
      question: 'Why might governments tax cigarettes more heavily than bread?',
      zh: '为什么政府可能对香烟征收比面包更高的税？',
      answer: 'Cigarettes create health costs and are demerit goods, while bread is a basic necessity.',
      answerZh: '香烟会带来健康成本，属于有害品；面包则是基本必需品。',
      visual: photos.tobacco,
    },
    {
      type: 'flow',
      eyebrow: 'Example',
      title:   'Indirect tax on tobacco',
      zhTitle: '烟草间接税',
      question: 'Many governments put high indirect taxes on cigarettes.',
      nodes: [['tax per packet rises', 'retail price rises', 'some smokers buy fewer cigarettes', 'health costs may fall']],
      footer: 'Limitation: addiction can make demand price inelastic, so quantity may fall only slightly.',
      visual: photos.tobacco,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'term',
      eyebrow: 'Learn',
      title:   'Import tariff',
      zhTitle: '进口关税',
      term:    'tariff',
      definition: 'A tariff is an indirect tax on imported goods. It raises the price of imports and may protect domestic producers.',
      definitionZh: '关税是对进口商品征收的间接税。它提高进口品价格，并可能保护国内生产者。',
      examples: ['tax on imported cars', 'import duty on steel', 'tariff on imported clothing'],
      visual: photos.port,
      partialReview: ['.termBox', '.choices > .choice'],
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'At the port',
      question: 'If a tariff makes imported phones more expensive, who might gain and who might lose?',
      zh: '如果关税使进口手机更贵，谁可能受益，谁可能受损？',
      answer: 'Domestic producers and the government may gain, while consumers and foreign producers may lose.',
      answerZh: '国内生产者和政府可能受益，消费者和外国生产者可能受损。',
      visual: photos.port,
    },
    {
      type: 'fact',
      eyebrow: 'Example',
      facts: {
        left: {
          flag: '🇸🇪',
          country: 'Sweden',
          context: 'Sweden’s carbon tax started at SEK 250 per tonne of fossil CO2 (about RMB 180) in 1991.',
          question: 'How could a pollution charge or carbon market reduce external costs?',
          questionZh: '污染收费或碳市场会如何减少外部成本？',
          answer: 'The third party is people affected by pollution; they face health costs that are not fully paid by producers or consumers.',
          zh: '1991年，瑞典碳税为每吨化石二氧化碳250瑞典克朗（约180元人民币）。',
          source: 'Source: Government Offices of Sweden; RMB conversion approximate.',
        },
        china: {
          flag: '🇨🇳',
          country: 'China',
          context: 'China’s national carbon market started in 2021, covering over 4.5 billion tonnes of CO2.',
          question: 'How could a pollution charge or carbon market reduce external costs?',
          questionZh: '污染收费或碳市场会如何减少外部成本？',
          answer: 'The third party is people affected by pollution; they face health costs that are not fully paid by producers or consumers.',
          zh: '中国全国碳市场2021年启动，覆盖超过45亿吨二氧化碳排放。',
          source: 'Source: Gov.cn and MEE reporting.',
        },
      },
      visual: factPhotos.swedenCarbon,
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'The smoke stack',
      question: 'Should a factory pay tax for pollution if it provides jobs in the local area?',
      zh: '如果工厂为当地提供就业，它还应该为污染纳税吗？',
      answer: 'It may still be taxed because pollution creates external costs, but the tax should consider jobs and competitiveness.',
      answerZh: '它仍可能应纳税，因为污染产生外部成本，但税收也应考虑就业和竞争力。',
      visual: photos.pollution,
    },
    {
      type: 'compare',
      eyebrow: 'Learn',
      title:   'Progressive and regressive taxes',
      leftTitle: 'Progressive tax',
      left: [
        'takes a higher proportion of income as income rises',
        'example: income tax with higher rates for higher income bands',
        'often used to reduce inequality'
      ],
      rightTitle: 'Regressive tax',
      right: [
        'takes a higher proportion of income from lower-income households',
        'example: indirect tax (sales tax)',
        'may increase inequality'
      ],
      visual: photos.shopping,
      partialReview: ['.splitCols > .card', '.prompt'],
    },
    {
      type: 'taxSim',
      eyebrow: 'Explore',
      title:   'Progressive or regressive?',
      defaultMode: 'progressive',
    },
    {
      type: 'chinaIncomeTaxSim',
      eyebrow: 'Example',
      title:   'Mainland China income tax',
      defaultIncome: 240000,
      standardDeduction: 60000,
      presets: [96000, 180000, 360000, 720000, 1200000],
      source: 'Resident comprehensive income; simplified classroom estimate. Sources: STA Individual Income Tax Law; PwC Worldwide Tax Summaries.',
    },
    {
      type: 'flow',
      eyebrow: 'Example',
      title:   'Why a sales tax can be regressive',
      zhTitle: '销售税可能具有累退性',
      question: 'Two households both pay $500 sales tax in a year.',
      nodes: [['low income: $10,000', '$500 is 5% of income', 'high income: $100,000', '$500 is 0.5% of income']],
      footer: 'The same tax payment is a larger proportion of the poorer household income.',
      visual: photos.shopping,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'term',
      eyebrow: 'Learn',
      title:   'Proportional tax',
      zhTitle: '比例税',
      term:    'proportional tax',
      definition: 'A proportional tax takes the same percentage of income from all taxpayers, even though higher earners pay more money in total.',
      definitionZh: '比例税从所有纳税人收入中征收相同百分比，虽然高收入者缴纳的总金额更多。',
      examples: ['10% of $20,000 = $2,000', '10% of $80,000 = $8,000', 'same percentage, different amount'],
      visual: photos.taxForms,
      partialReview: ['.termBox', '.choices > .choice'],
    },
    {
      type: 'quiz',
      eyebrow: 'Check',
      title:   'Classify the tax',
      question: 'A government charges a percentage tax on company profits and uses the revenue to fund schools.',
      choices: [
        'Direct tax and corporation tax',
        'Indirect tax on spending',
        'Tariff and regressive tax',
      ],
      prompt: 'Add one possible effect on firms.',
      visual: photos.industry,
    },
    {
      type: 'quiz',
      eyebrow: 'Check',
      title:   'Pick the best explanation',
      question: 'Why might a government increase tax on petrol?',
      choices: [
        'To raise revenue and discourage pollution from car use',
        'To make exports cheaper',
        'To increase disposable income',
      ],
      prompt: 'Now add one limitation of the policy.',
      visual: photos.pollution,
    },
    {
      type: 'answer',
      eyebrow: 'Check',
      title:   'Exit ticket',
      zhTitle: '离堂小测',
      steps: [
        ['1', 'A direct tax is paid on income, profit or __________.'],
        ['2', 'An indirect tax is paid when goods and services are __________.'],
        ['3', 'A tariff is a tax on __________.'],
        ['4', 'A progressive tax takes a higher __________ as income rises.'],
      ],
      cue: 'Answer before moving from taxation to wider fiscal policy.',
      visual: photos.classroom,
      partialReview: ['.steps > .step', '.prompt'],
    },
    {
      type: 'compare',
      eyebrow: 'Learn',
      title:   'Direct or indirect?',
      leftTitle:  'Direct tax',
      left:  ['on income or wealth', 'paid directly to government'],
      rightTitle: 'Indirect tax',
      right: ['on spending', 'paid when goods or services are bought'],
      prompt: 'Classify: income tax, VAT, corporation tax, tariff.',
      visual: photos.taxForms,
      partialReview: ['.splitCols > .card', '.prompt'],
    },
    {
      type: 'compare',
      eyebrow: 'Learn',
      title:   'Progressive or regressive?',
      leftTitle:  'Progressive',
      left:  ['higher proportion as income rises'],
      rightTitle: 'Regressive',
      right: ['higher proportion for lower-income groups'],
      visual: photos.socialSecurity,
      partialReview: ['.splitCols > .card', '.prompt'],
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'Reducing inequality',
      question: 'Which tax structure reduces inequality more directly?',
      zh: '哪种税收结构更直接地减少不平等？',
      answer: 'Progressive tax reduces inequality more directly because the tax rate rises as income rises.',
      answerZh: '累进税更直接减少不平等，因为收入越高，税率越高。',
      visual: photos.socialSecurity,
    },
    {
      type: 'term',
      eyebrow: 'Learn',
      title:   'Proportional tax',
      zhTitle: '比例税',
      term:    'proportional tax',
      definition: 'A tax that takes the same proportion of income at all income levels.',
      definitionZh: '对所有收入水平征收相同比例收入的税。',
      examples: ['15% of $20,000', '15% of $80,000'],
      visual:  photos.taxForms,
      partialReview: ['.termBox', '.choices > .choice'],
    },
    {
      type: 'cards',
      eyebrow: 'Exam practice',
      title:   'Classify before explaining',
      lead:    'A strong answer names the tax type, then links it to a macroeconomic aim.',
      cards: [
        ['Direct or indirect?', 'what is being taxed? income, wealth, or spending?'],
        ['Progressive?', 'does the proportion rise as income rises?'],
        ['Regressive?', 'does the proportion hit lower-income households harder?'],
        ['Proportional?', 'is the same percentage charged at all income levels?'],
      ],
      visual: photos.taxForms,
      partialReview: ['.cardgrid > .card', '.prompt'],
    },
    {
      type: 'discussion',
      eyebrow: 'Exam practice',
      title:   'Regressive taxes',
      question: 'Why might a sales tax be called regressive?',
      zh: '为什么销售税可能被称为累退税？',
      answer: 'It can take a larger percentage of income from poorer households because they spend most of their income.',
      answerZh: '因为较贫困家庭会花掉大部分收入，销售税可能占他们收入的更高比例。',
      visual: photos.shopping,
    },

    {
      type: 'section',
      eyebrow: 'New section',
      title:   'Fiscal policy',
      zhTitle: '财政政策',
      subtitle: 'Changes in spending and taxation are used to influence macroeconomic aims.',
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'Changing the economy',
      question: 'Can a government change the whole economy by changing spending and taxes?',
      zh: '政府能通过改变支出和税收来影响整个经济吗？',
      answer: 'Yes. Fiscal policy can change aggregate demand, which affects output, employment, prices and growth.',
      answerZh: '可以。财政政策会改变总需求，从而影响产出、就业、价格和经济增长。',
      visual: photos.budgetMeeting,
    },
    {
      type: 'term',
      eyebrow: 'Learn',
      title:   'Fiscal policy',
      zhTitle: '财政政策',
      term:    'fiscal policy',
      definition: 'The use of government spending and taxation to influence economic activity, aggregate demand and macroeconomic aims.',
      definitionZh: '政府利用支出和税收来影响经济活动、总需求和宏观经济目标。',
      examples: ['government spending', 'taxation', 'macroeconomic aims'],
      visual: photos.budgetMeeting,
      partialReview: ['.termBox', '.choices > .choice'],
    },
    {
      type: 'compare',
      eyebrow: 'Learn',
      title:   'The two fiscal-policy measures',
      leftTitle:  'Government spending',
      left:  ['increase spending to raise demand or improve supply', 'reduce spending to lower demand or borrowing'],
      rightTitle: 'Taxation',
      right: ['cut taxes to raise disposable income or incentives', 'raise taxes to reduce demand or fund spending'],
      prompt: 'Every fiscal-policy answer should mention spending and/or taxation.',
      visual: photos.budgetMeeting,
      partialReview: ['.splitCols > .card', '.prompt'],
    },
    {
      type: 'fact',
      eyebrow: 'Example',
      facts: {
        left: {
          flag: '🇸🇬',
          country: 'Singapore',
          context: 'Singapore added S$1.9 billion (about RMB 10 billion) for cost-of-living relief in Budget 2024.',
          question: 'Which fiscal-policy concept does this example show?',
          questionZh: '这个例子说明了哪个经济概念？',
          answer: 'A strong answer should name the concept, link the context to the first economic effect, and then explain the likely outcome.',
          zh: '新加坡2024年预算案增加19亿新元（约100亿元人民币）缓解生活成本压力。',
          source: 'Source: Singapore Ministry of Finance; RMB conversion approximate.',
        },
        china: {
          flag: '🇨🇳',
          country: 'China',
          context: 'China planned RMB 28.5 trillion in general public budget spending for 2024.',
          question: 'Which fiscal-policy concept does this example show?',
          questionZh: '这个例子说明了哪个经济概念？',
          answer: 'A strong answer should name the concept, link the context to the first economic effect, and then explain the likely outcome.',
          zh: '中国2024年一般公共预算支出安排28.5万亿元人民币。',
          source: 'Source: 2024 Government Work Report.',
        },
      },
      visual: factPhotos.singaporeBudget,
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'Stimulus',
      question: 'When unemployment is high, should the government cut taxes or increase spending?',
      zh: '当失业率较高时，政府应该减税还是增加支出？',
      answer: 'Either can be expansionary: tax cuts raise disposable income, while higher spending directly raises demand.',
      answerZh: '两者都可以是扩张性的：减税提高可支配收入，增加支出则直接提高需求。',
      visual: photos.roadwork,
    },
    {
      type: 'flow',
      eyebrow: 'Learn',
      title:   'Expansionary policy',
      zhTitle: '扩张性政策',
      nodes: [['higher spending or lower taxes', 'aggregate demand rises', 'firms may increase output', 'growth and employment may rise']],
      footer: 'Risk: inflation and imports may rise.',
      visual: photos.roadwork,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'Cooling demand',
      question: 'When prices are rising too quickly, should the government raise taxes or cut spending?',
      zh: '当价格上涨过快时，政府应该增税还是削减支出？',
      answer: 'Either can reduce aggregate demand, but both may slow growth or increase unemployment.',
      answerZh: '两者都可以降低总需求，但也可能放慢增长或增加失业。',
      visual: photos.inflation,
    },
    {
      type: 'flow',
      eyebrow: 'Learn',
      title:   'Contractionary policy',
      zhTitle: '紧缩性政策',
      nodes: [['lower spending or higher taxes', 'aggregate demand falls', 'spending pressure eases', 'inflationary pressure may fall']],
      footer: 'Risk: output and employment may fall.',
      visual: photos.taxForms,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'discussion',
      eyebrow: 'Explore',
      title:   'Policy conflicts',
      question: 'Which macroeconomic aim is most likely to conflict with lower inflation?',
      zh: '哪个宏观经济目标最可能与降低通货膨胀发生冲突？',
      answer: 'Lower inflation may conflict with employment or economic growth if policy reduces aggregate demand.',
      answerZh: '如果政策降低总需求，降低通胀可能与就业或经济增长发生冲突。',
      visual: photos.budgetMeeting,
    },
    {
      type: 'cards',
      eyebrow: 'Learn',
      title:   'Fiscal policy and macro aims',
      lead:    'Each aim needs a clear spending or tax chain.',
      cards: [
        ['Growth', 'raise demand or improve supply'],
        ['Employment', 'increase demand for labour'],
        ['Price stability', 'reduce inflation pressure'],
        ['Redistribution', 'reduce income inequality'],
        ['Balance of payments', 'reduce imports'],
        ['Sustainability', 'change environmental incentives'],
      ],
      footer: 'Evaluation: identify a possible conflict or time lag.',
      visual: photos.budgetMeeting,
      partialReview: ['.cardgrid > .card', '.prompt'],
    },
    {
      type: 'flow',
      eyebrow: 'Learn',
      title:   'Economic growth',
      zhTitle: '经济增长',
      nodes: [['higher spending or lower taxes', 'aggregate demand rises', 'firms produce more', 'real GDP may rise']],
      footer: 'Risk: inflation or imports may also rise.',
      visual: photos.roadwork,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'flow',
      eyebrow: 'Learn',
      title:   'Employment',
      zhTitle: '就业',
      nodes: [['higher demand for goods', 'firms increase output', 'firms hire more workers', 'unemployment may fall']],
      footer: 'Risk: this may be slow if workers lack the right skills.',
      visual: photos.industry,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'flow',
      eyebrow: 'Learn',
      title:   'Price stability',
      zhTitle: '价格稳定',
      nodes: [['higher taxes or lower spending', 'aggregate demand falls', 'spending pressure eases', 'inflation may fall']],
      footer: 'Risk: output and employment may fall.',
      visual: photos.inflation,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'flow',
      eyebrow: 'Learn',
      title:   'Redistribution',
      zhTitle: '再分配',
      nodes: [['progressive taxes', 'revenue funds welfare', 'poorer households receive support', 'inequality may fall']],
      footer: 'Risk: high tax rates may reduce incentives for some workers or firms.',
      visual: photos.socialSecurity,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'flow',
      eyebrow: 'Learn',
      title:   'Balance of payments',
      zhTitle: '国际收支',
      nodes: [['higher taxes', 'consumer spending falls', 'imports may fall', 'current account may improve']],
      footer: 'Risk: lower demand can also reduce economic growth.',
      visual: photos.port,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'flow',
      eyebrow: 'Learn',
      title:   'Sustainability',
      zhTitle: '可持续发展',
      nodes: [['green taxes or spending', 'incentives change', 'pollution may fall', 'sustainability may improve']],
      footer: 'Risk: firms may pass higher costs to consumers.',
      visual: photos.pollution,
      partialReview: ['.flowRow > .flowChip', '.prompt'],
    },
    {
      type: 'exam',
      eyebrow: 'Exam practice',
      title:   'Explain chain',
      question: 'Explain how an increase in government spending on infrastructure may help economic growth.',
      keywords: ['infrastructure', 'costs', 'investment', 'real GDP'],
      prompt:   'Write one clear chain and use "may".',
      visual:   photos.roadwork,
      partialReview: ['.cardgrid > .card', '.prompt'],
    },
    {
      type: 'modelAnswer',
      eyebrow: 'Exam answer',
      title:   'Model answer',
      question: 'Explain how an increase in government spending on infrastructure may help economic growth.',
      answer: 'Higher government spending on infrastructure can improve roads, ports or digital networks. This may reduce firms\' costs and make production more efficient. Lower costs can encourage investment and allow firms to produce more output, so real GDP and economic growth may rise.',
      links: ['infrastructure', 'costs', 'investment', 'real GDP'],
      markSchemeNote: 'This matches explain wording by identifying the spending area and developing a clear transmission chain to real GDP.',
      partialReview: ['.modelAnswerCard', '.modelAnswerLinks > span', '.modelAnswerNote'],
    },
    {
      type: 'exam',
      eyebrow: 'Exam practice',
      title:   'Discuss two sides',
      question: 'Discuss whether cutting taxes is the best way for a government to reduce unemployment.',
      keywords: ['disposable income', 'aggregate demand', 'employment', 'inflation', 'budget deficit'],
      prompt:   'Build one argument for, one against, then make a judgement.',
      visual:   photos.shopping,
      partialReview: ['.cardgrid > .card', '.prompt'],
    },
    {
      type: 'modelAnswer',
      eyebrow: 'Exam answer',
      title:   'Model answer',
      question: 'Discuss whether cutting taxes is the best way for a government to reduce unemployment.',
      answer: 'Cutting taxes can raise disposable income, so consumers may spend more. This increases aggregate demand, encouraging firms to produce more and employ more workers. However, higher demand may cause inflation or increase imports, and lower tax revenue may increase the budget deficit. It is best if unemployment is caused by weak demand, but supply-side policies may work better for structural unemployment.',
      links: ['disposable income', 'aggregate demand', 'employment', 'inflation', 'budget deficit'],
      markSchemeNote: 'This follows discuss level wording by analysing the benefit, considering risks, and making a conditional judgement.',
      partialReview: ['.modelAnswerCard', '.modelAnswerLinks > span', '.modelAnswerNote'],
    },
    {
      type: 'answer',
      eyebrow: 'Check',
      title:   'Exit ticket',
      zhTitle: '离堂小测',
      steps: [
        ['1', 'Fiscal policy uses government __________ and taxation.'],
        ['2', 'A budget deficit means spending is __________ revenue.'],
        ['3', 'Higher taxes may reduce __________-pull inflation.'],
      ],
      cue: 'Answer before leaving.',
      visual: photos.classroom,
      partialReview: ['.steps > .step', '.prompt'],
    },
  ],
};
